import type { TmdIcon } from './build/my-icons.model';
export type TmdIconNameSubset<T extends Readonly<TmdIcon[]>> = T[number]['name'];
export * from './build/ng-arrow-up.icon';
export * from './build/ng-down-arrow.icon';
export * from './build/ng-favicon.icon';
export * from './build/ng-hemburg.icon';
export * from './build/ng-logo-dark.icon';
export * from './build/ng-logo-light.icon';
export * from './build/ng-right-arrow.icon';
export * from './build/ng-search.icon';
export * from './build/ng-x-close.icon';
export * from './build/ng-email.icon';
export * from './build/ng-github.icon';
export * from './build/ng-linkedin.icon';
export * from './build/my-icons.model';
