import { GameModel, GameMenuModel, MenuListModel, GameModelHot, CategoryListModel } from "../app/_model";
import { environment } from "../environments/environment";
export const GameList: Array<GameMenuModel> = [
  {
    id: '2',
    title: 'recent',
    index: 0,
    gameList: [
      {
        id: '10',
        title: 'Flight Sim',
        description: '',
        thumb: `/assets/updated-games/flight-sim/bg-square.jpg`,
        thumbBig: `/assets/updated-games/flight-sim/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/flight-sim/index.html`,
        categoryId: '3',
        sortOrder: 1,
      },
      {
        id: '28',
        title: 'Crazy Runner',
        description: '',
        thumb: `/assets/updated-games/crazy-runner/bg-square.jpg`,
        thumbBig: `/assets/updated-games/crazy-runner/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/crazy-runner/index.html`,
        categoryId: '6',
        sortOrder: 1,
      },
      {
        id: '16',
        title: 'Ludo Multiplayer',
        description: '',
        thumb: `/assets/updated-games/ludo-multiplayer/bg-square.jpg`,
        thumbBig: `/assets/updated-games/ludo-multiplayer/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/ludo-multiplayer/index.html`,
        categoryId: '5',
        sortOrder: 1,
      },
      {
        id: '18',
        title: 'Pacman',
        description: '',
        thumb: `/assets/updated-games/pacman-canvas/bg-square.jpg`,
        thumbBig: `/assets/updated-games/pacman-canvas/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/pacman-canvas/index.html`,
        categoryId: '5',
        sortOrder: 1,
      },
      {
        id: '19',
        title: 'Quiz Game 2',
        description: '',
        thumb: `/assets/updated-games/quiz-game-2/bg-square.jpg`,
        thumbBig: `/assets/updated-games/quiz-game-2/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/quiz-game-2/index.html`,
        categoryId: '5',
        sortOrder: 1,
      },
      {
        id: '26',
        title: 'Super Cowboy Run',
        description: '',
        thumb: `/assets/updated-games/super-cowboy-run/bg-square.jpg`,
        thumbBig: `/assets/updated-games/super-cowboy-run/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/super-cowboy-run/index.html`,
        categoryId: '6',
        sortOrder: 1,
      },
      {
        id: '27',
        title: 'Duck Shooter',
        description: '',
        thumb: `/assets/updated-games/duck-shooter/bg-square.jpg`,
        thumbBig: `/assets/updated-games/duck-shooter/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/duck-shooter/index.html`,
        categoryId: '7',
        sortOrder: 1,
      },
      {
        id: '29',
        title: 'Fishing Frenzy',
        description: '',
        thumb: `/assets/updated-games/fishing-frenzy/bg-square.jpg`,
        thumbBig: `/assets/updated-games/fishing-frenzy/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/fishing-frenzy/index.html`,
        categoryId: '9',
        sortOrder: 1,
      },
      {
        id: '30',
        title: 'Space Purge',
        description: '',
        thumb: `/assets/updated-games/space-purge/bg-square.jpg`,
        thumbBig: `/assets/updated-games/space-purge/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/space-purge/index.html`,
        categoryId: '9',
        sortOrder: 1,
      },
      {
        id: '31',
        title: 'Tank Defender',
        description: '',
        thumb: `/assets/updated-games/tank-defender/bg-square.jpg`,
        thumbBig: `/assets/updated-games/tank-defender/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/tank-defender/index.html`,
        categoryId: '9',
        sortOrder: 1,
      },
      {
        id: '33',
        title: 'Ninja Run',
        description: '',
        thumb: `/assets/updated-games/ninja-run/bg-square.jpg`,
        thumbBig: `/assets/updated-games/ninja-run/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/ninja-run/index.html`,
        categoryId: '9',
        sortOrder: 1,
      },
    ]
  },
  {
    id: '3',
    title: 'trending',
    index: 0,
    gameList: [
      {
        id: '2',
        title: 'Bamses Treasure',
        description: '',
        thumb: `/assets/updated-games/bamses-treasure/bg-square.jpg`,
        thumbBig: `/assets/updated-games/bamses-treasure/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/bamses-treasure/index.html`,
        categoryId: '1',
        sortOrder: 1,
      },
      {
        id: '3',
        title: 'Penalty Kicks',
        description: '',
        thumb: `/assets/updated-games/penalty-kicks/bg-square.jpg`,
        thumbBig: `/assets/updated-games/penalty-kicks/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/penalty-kicks/index.html`,
        categoryId: '1',
        sortOrder: 1,
      },
      {
        id: '4',
        title: 'Jump Ninja Hero',
        description: '',
        thumb: `/assets/updated-games/jump-ninja-hero/bg-square.jpg`,
        thumbBig: `/assets/updated-games/jump-ninja-hero/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/jump-ninja-hero/index.html`,
        categoryId: '1',
        sortOrder: 1,
      },
      {
        id: '5',
        title: 'The fruits',
        description: '',
        thumb: `/assets/updated-games/the-fruits/bg-square.jpg`,
        thumbBig: `/assets/updated-games/the-fruits/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/the-fruits/index.html`,
        categoryId: '2',
        sortOrder: 14
      },
      {
        id: '6',
        title: 'Jelly Break',
        description: '',
        thumb: `/assets/updated-games/jelly-break/bg-square.jpg`,
        thumbBig: `/assets/updated-games/jelly-break/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/jelly-break/index.html`,
        categoryId: '1',
        sortOrder: 1,
      },
      {
        id: '7',
        title: 'Classic Bowling',
        description: '',
        thumb: `/assets/updated-games/classic-bowling/bg-square.jpg`,
        thumbBig: `/assets/updated-games/classic-bowling/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/classic-bowling/index.html`,
        categoryId: '1',
        sortOrder: 1,
      },
      {
        id: '8',
        title: '2048 master',
        description: '',
        thumb: `/assets/updated-games/2048-master/bg-square.jpg`,
        thumbBig: `/assets/updated-games/2048-master/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/2048-master/index.html`,
        categoryId: '2',
        sortOrder: 1,
      },
      {
        id: '9',
        title: 'Bingo',
        description: '',
        thumb: `/assets/updated-games/bingo/bg-square.jpg`,
        thumbBig: `/assets/updated-games/bingo/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/bingo/index.html`,
        categoryId: '1',
        sortOrder: 1,
      },
      {
        id: '10',
        title: 'Flight Sim',
        description: '',
        thumb: `/assets/updated-games/flight-sim/bg-square.jpg`,
        thumbBig: `/assets/updated-games/flight-sim/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/flight-sim/index.html`,
        categoryId: '3',
        sortOrder: 1,
      },
      {
        id: '26',
        title: 'Super Cowboy Run',
        description: '',
        thumb: `/assets/updated-games/super-cowboy-run/bg-square.jpg`,
        thumbBig: `/assets/updated-games/super-cowboy-run/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/super-cowboy-run/index.html`,
        categoryId: '6',
        sortOrder: 1,
      },
      {
        id: '27',
        title: 'Duck Shooter',
        description: '',
        thumb: `/assets/updated-games/duck-shooter/bg-square.jpg`,
        thumbBig: `/assets/updated-games/duck-shooter/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/duck-shooter/index.html`,
        categoryId: '7',
        sortOrder: 1,
      },
      {
        id: '28',
        title: 'Crazy Runner',
        description: '',
        thumb: `/assets/updated-games/crazy-runner/bg-square.jpg`,
        thumbBig: `/assets/updated-games/crazy-runner/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/crazy-runner/index.html`,
        categoryId: '6',
        sortOrder: 1,
      },
      {
        id: '29',
        title: 'Fishing Frenzy',
        description: '',
        thumb: `/assets/updated-games/fishing-frenzy/bg-square.jpg`,
        thumbBig: `/assets/updated-games/fishing-frenzy/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/fishing-frenzy/index.html`,
        categoryId: '9',
        sortOrder: 1,
      },
    ]
  },
  {
    id: '4',
    title: 'featured',
    index: 0,
    gameList: [
      {
        id: '54',
        title: 'Candymatch3',
        description: '',
        thumb: `/assets/updated-games/candymatch3/bg-square.jpg`,
        thumbBig: `/assets/updated-games/candymatch3/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/candymatch3/index.html`,
        categoryId: '4',
        sortOrder: 1,

      },
      {
        id: '55',
        title: 'Kids True Color',
        description: '',
        thumb: `/assets/updated-games/kids-true-color/bg-square.jpg`,
        thumbBig: `/assets/updated-games/kids-true-color/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/kids-true-color/index.html`,
        categoryId: '5',
        sortOrder: 1,

      },
      {
        id: '56',
        title: 'Christmas Balloons',
        description: '',
        thumb: `/assets/updated-games/christmas-balloons/bg-square.jpg`,
        thumbBig: `/assets/updated-games/christmas-balloons/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/christmas-balloons/index.html`,
        categoryId: '6',
        sortOrder: 1,

      },
      {
        id: '57',
        title: 'Christmas Match',
        description: '',
        thumb: `/assets/updated-games/christmasmatch/bg-square.jpg`,
        thumbBig: `/assets/updated-games/christmasmatch/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/christmasmatch/index.html`,
        categoryId: '6',
        sortOrder: 1,

      },
      {
        id: '58',
        title: 'Speed Racer',
        description: '',
        thumb: `/assets/updated-games/speedracer/bg-square.jpg`,
        thumbBig: `/assets/updated-games/speedracer/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/speedracer/index.html`,
        categoryId: '6',
        sortOrder: 1,

      },
      {
        id: '59',
        title: 'Christmas PandaRun',
        description: '',
        thumb: `/assets/updated-games/christmaspandarun/bg-square.jpg`,
        thumbBig: `/assets/updated-games/christmaspandarun/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/christmaspandarun/index.html`,
        categoryId: '7',
        sortOrder: 1,

      },
      {
        id: '60',
        title: 'Shoot Robbers',
        description: '',
        thumb: `/assets/updated-games/shootrobbers/bg-square.jpg`,
        thumbBig: `/assets/updated-games/shootrobbers/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/shootrobbers/index.html`,
        categoryId: '8',
        sortOrder: 1,

      },
      {
        id: '61',
        title: 'JellyMatch3',
        description: '',
        thumb: `/assets/updated-games/jellymatch3/bg-square.jpg`,
        thumbBig: `/assets/updated-games/jellymatch3/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/jellymatch3/index.html`,
        categoryId: '9',
        sortOrder: 1,

      },
      {
        id: '62',
        title: 'Candy super Lines',
        description: '',
        thumb: `/assets/updated-games/candysuperlines/bg-square.jpg`,
        thumbBig: `/assets/updated-games/candysuperlines/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/candysuperlines/index.html`,
        categoryId: '10',
        sortOrder: 1,

      },
      {
        id: '63',
        title: 'GirlDressUp',
        description: '',
        thumb: `/assets/updated-games/girldressup/bg-square.jpg`,
        thumbBig: `/assets/updated-games/girldressup/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/girldressup/index.html`,
        categoryId: '1',
        sortOrder: 1,

      },
      {
        id: '64',
        title: 'Traffic',
        description: '',
        thumb: `/assets/updated-games/traffic/bg-square.jpg`,
        thumbBig: `/assets/updated-games/traffic/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/traffic/index.html`,
        categoryId: '2',
        sortOrder: 1,

      },
      {
        id: '65',
        title: 'Halloween Bubble Shooter',
        description: '',
        thumb: `/assets/updated-games/halloweenbubbleshooter/bg-square.jpg`,
        thumbBig: `/assets/updated-games/halloweenbubbleshooter/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/halloweenbubbleshooter/index.html`,
        categoryId: '2',
        sortOrder: 1,

      },
      {
        id: '14',
        title: 'Flip Card Memory Test',
        description: '',
        thumb: `/assets/updated-games/flip-card/bg-square.jpg`,
        thumbBig: `/assets/updated-games/flip-card/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/flip-card/index.html`,
        categoryId: '4',
        sortOrder: 1,
      },
    ]
  },
  {
    id: '4',
    title: 'latest',
    index: 0,
    gameList: [
      {
        id: '67',
        title: 'Ranger-Zombies',
        description: '',
        thumb: `/assets/updated-games/ranger-vs-zombies/bg-square.jpg`,
        thumbBig: `/assets/updated-games/ranger-vs-zombies/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/ranger-vs-zombies/index.html`,
        categoryId: '3',
        sortOrder: 1,

      },
      {
        id: '68',
        title: 'Brickout',
        description: '',
        thumb: `/assets/updated-games/brickout/bg-square.jpg`,
        thumbBig: `/assets/updated-games/brickout/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/brickout/index.html`,
        categoryId: '3',
        sortOrder: 1,

      },
      {
        id: '69',
        title: 'Fruitsnake',
        description: '',
        thumb: `/assets/updated-games/fruitsnake/bg-square.jpg`,
        thumbBig: `/assets/updated-games/fruitsnake/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/fruitsnake/index.html`,
        categoryId: '4',
        sortOrder: 1,

      },
      {
        id: '70',
        title: 'Fruitslasher',
        description: '',
        thumb: `/assets/updated-games/fruitslasher/bg-square.jpg`,
        thumbBig: `/assets/updated-games/fruitslasher/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/fruitslasher/index.html`,
        categoryId: '5',
        sortOrder: 1,

      },
      {
        id: '71',
        title: 'Tankwars',
        description: '',
        thumb: `/assets/updated-games/tankwars/bg-square.jpg`,
        thumbBig: `/assets/updated-games/tankwars/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/tankwars/index.html`,
        categoryId: '6',
        sortOrder: 1,

      },
      {
        id: '72',
        title: 'Cartoon Candy',
        description: '',
        thumb: `/assets/updated-games/cartoon-candy-match3/bg-square.jpg`,
        thumbBig: `/assets/updated-games/cartoon-candy-match3/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/cartoon-candy-match3/index.html`,
        categoryId: '7',
        sortOrder: 1,

      },
      {
        id: '73',
        title: 'Flappyball',
        description: '',
        thumb: `/assets/updated-games/flappyball/bg-square.jpg`,
        thumbBig: `/assets/updated-games/flappyball/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/flappyball/index.html`,
        categoryId: '7',
        sortOrder: 1,

      },
      {
        id: '74',
        title: 'Fishworld Match3',
        description: '',
        thumb: `/assets/updated-games/fishworld-match3/bg-square.jpg`,
        thumbBig: `/assets/updated-games/fishworld-match3/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/fishworld-match3/index.html`,
        categoryId: '7',
        sortOrder: 1,

      },
      {
        id: '75',
        title: '2048 Master',
        description: '',
        thumb: `/assets/updated-games/2048-master/bg-square.jpg`,
        thumbBig: `/assets/updated-games/2048-master/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/2048-master/index.html`,
        categoryId: '7',
        sortOrder: 1,

      },
      {
        id: '76',
        title: 'Race Master',
        description: '',
        thumb: `/assets/updated-games/race-master/bg-square.jpg`,
        thumbBig: `/assets/updated-games/race-master/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/race-master/index.html`,
        categoryId: '7',
        sortOrder: 1,

      },
      {
        id: '67',
        title: 'Ranger-Zombies',
        description: '',
        thumb: `/assets/updated-games/ranger-vs-zombies/bg-square.jpg`,
        thumbBig: `/assets/updated-games/ranger-vs-zombies/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/ranger-vs-zombies/index.html`,
        categoryId: '3',
        sortOrder: 1,

      },
      {
        id: '68',
        title: 'Brickout',
        description: '',
        thumb: `/assets/updated-games/brickout/bg-square.jpg`,
        thumbBig: `/assets/updated-games/brickout/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/brickout/index.html`,
        categoryId: '3',
        sortOrder: 1,

      },
      {
        id: '69',
        title: 'Fruitsnake',
        description: '',
        thumb: `/assets/updated-games/fruitsnake/bg-square.jpg`,
        thumbBig: `/assets/updated-games/fruitsnake/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/fruitsnake/index.html`,
        categoryId: '4',
        sortOrder: 1,

      },
      {
        id: '70',
        title: 'Fruitslasher',
        description: '',
        thumb: `/assets/updated-games/fruitslasher/bg-square.jpg`,
        thumbBig: `/assets/updated-games/fruitslasher/bg-thumbnail.jpg`,
        url: `${environment.gameUrl}/fruitslasher/index.html`,
        categoryId: '5',
        sortOrder: 1,

      },
    ]
  },
];
export const GameListCategory: Array<GameModel> = [
  {
    id: '70',
    title: 'Fruitslasher',
    description: '',
    thumb: `/assets/updated-games/fruitslasher/bg-square.jpg`,
    thumbBig: `/assets/updated-games/fruitslasher/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/fruitslasher/index.html`,
    categoryId: '5',
    sortOrder: 1,

  },
  {
    id: '2',
    title: 'Bamses Treasure',
    description: '',
    thumb: `/assets/updated-games/bamses-treasure/bg-square.jpg`,
    thumbBig: `/assets/updated-games/bamses-treasure/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/bamses-treasure/index.html`,
    categoryId: '1',
    sortOrder: 3,
  },
  {
    id: '3',
    title: 'Penalty Kicks',
    description: '',
    thumb: `/assets/updated-games/penalty-kicks/bg-square.jpg`,
    thumbBig: `/assets/updated-games/penalty-kicks/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/penalty-kicks/index.html`,
    categoryId: '1',
    sortOrder: 1,
  },
  {
    id: '4',
    title: 'Jump Ninja Hero',
    description: '',
    thumb: `/assets/updated-games/jump-ninja-hero/bg-square.jpg`,
    thumbBig: `/assets/updated-games/jump-ninja-hero/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/jump-ninja-hero/index.html`,
    categoryId: '1',
    sortOrder: 1,
  },
  {
    id: '5',
    title: 'The fruits',
    description: '',
    thumb: `/assets/updated-games/the-fruits/bg-square.jpg`,
    thumbBig: `/assets/updated-games/the-fruits/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/the-fruits/index.html`,
    categoryId: '2',
    sortOrder: 3
  },
  {
    id: '6',
    title: 'Jelly Break',
    description: '',
    thumb: `/assets/updated-games/jelly-break/bg-square.jpg`,
    thumbBig: `/assets/updated-games/jelly-break/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/jelly-break/index.html`,
    categoryId: '4',
    sortOrder: 2,
  },
  {
    id: '7',
    title: 'Classic Bowling',
    description: '',
    thumb: `/assets/updated-games/classic-bowling/bg-square.jpg`,
    thumbBig: `/assets/updated-games/classic-bowling/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/classic-bowling/index.html`,
    categoryId: '1',
    sortOrder: 1,
  },
  {
    id: '9',
    title: 'Bingo',
    description: '',
    thumb: `/assets/updated-games/bingo/bg-square.jpg`,
    thumbBig: `/assets/updated-games/bingo/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/bingo/index.html`,
    categoryId: '8',
    sortOrder: 1,
  },
  {
    id: '10',
    title: 'Flight Sim',
    description: '',
    thumb: `/assets/updated-games/flight-sim/bg-square.jpg`,
    thumbBig: `/assets/updated-games/flight-sim/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/flight-sim/index.html`,
    categoryId: '3',
    sortOrder: 1,
  },
  {
    id: '14',
    title: 'Flip Card Memory Test',
    description: '',
    thumb: `/assets/updated-games/flip-card/bg-square.jpg`,
    thumbBig: `/assets/updated-games/flip-card/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/flip-card/index.html`,
    categoryId: '11',
    sortOrder: 5,
  },
  {
    id: '16',
    title: 'Ludo Multiplayer',
    description: '',
    thumb: `/assets/updated-games/ludo-multiplayer/bg-square.jpg`,
    thumbBig: `/assets/updated-games/ludo-multiplayer/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/ludo-multiplayer/index.html`,
    categoryId: '1',
    sortOrder: 2,
  },
  {
    id: '18',
    title: 'Pacman',
    description: '',
    thumb: `/assets/updated-games/pacman-canvas/bg-square.jpg`,
    thumbBig: `/assets/updated-games/pacman-canvas/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/pacman-canvas/index.html`,
    categoryId: '5',
    sortOrder: 2,
  },
  {
    id: '19',
    title: 'Quiz Game 2',
    description: '',
    thumb: `/assets/updated-games/quiz-game-2/bg-square.jpg`,
    thumbBig: `/assets/updated-games/quiz-game-2/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/quiz-game-2/index.html`,
    categoryId: '5',
    sortOrder: 3,
  },
  {
    id: '21',
    title: 'Tower',
    description: '',
    thumb: `/assets/updated-games/tower/bg-square.jpg`,
    thumbBig: `/assets/updated-games/tower/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/tower/index.html`,
    categoryId: '5',
    sortOrder: 3,
  },
  {
    id: '22',
    title: 'Tower Defense',
    description: '',
    thumb: `/assets/updated-games/tower-defense/bg-square.jpg`,
    thumbBig: `/assets/updated-games/tower-defense/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/tower-defense/index.html`,
    categoryId: '5',
    sortOrder: 5,
  },
  {
    id: '26',
    title: 'Super Cowboy Run',
    description: '',
    thumb: `/assets/updated-games/super-cowboy-run/bg-square.jpg`,
    thumbBig: `/assets/updated-games/super-cowboy-run/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/super-cowboy-run/index.html`,
    categoryId: '6',
    sortOrder: 1,
  },
  {
    id: '27',
    title: 'Duck Shooter',
    description: '',
    thumb: `/assets/updated-games/duck-shooter/bg-square.jpg`,
    thumbBig: `/assets/updated-games/duck-shooter/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/duck-shooter/index.html`,
    categoryId: '7',
    sortOrder: 1,
  },
  {
    id: '28',
    title: 'Crazy Runner',
    description: '',
    thumb: `/assets/updated-games/crazy-runner/bg-square.jpg`,
    thumbBig: `/assets/updated-games/crazy-runner/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/crazy-runner/index.html`,
    categoryId: '10',
    sortOrder: 1,
  },
  {
    id: '29',
    title: 'Fishing Frenzy',
    description: '',
    thumb: `/assets/updated-games/fishing-frenzy/bg-square.jpg`,
    thumbBig: `/assets/updated-games/fishing-frenzy/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/fishing-frenzy/index.html`,
    categoryId: '9',
    sortOrder: 1,
  },
  {
    id: '30',
    title: 'Space Purge',
    description: '',
    thumb: `/assets/updated-games/space-purge/bg-square.jpg`,
    thumbBig: `/assets/updated-games/space-purge/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/space-purge/index.html`,
    categoryId: '9',
    sortOrder: 1,
  },
  {
    id: '31',
    title: 'Tank Defender',
    description: '',
    thumb: `/assets/updated-games/tank-defender/bg-square.jpg`,
    thumbBig: `/assets/updated-games/tank-defender/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/tank-defender/index.html`,
    categoryId: '9',
    sortOrder: 1,
  },
  {
    id: '32',
    title: 'Casino Card Memory',
    description: '',
    thumb: `/assets/updated-games/casino-card-memory/bg-square.jpg`,
    thumbBig: `/assets/updated-games/casino-card-memory/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/casino-card-memory/index.html`,
    categoryId: '9',
    sortOrder: 1,
  },
  {
    id: '33',
    title: 'Ninja Run',
    description: '',
    thumb: `/assets/updated-games/ninja-run/bg-square.jpg`,
    thumbBig: `/assets/updated-games/ninja-run/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/ninja-run/index.html`,
    categoryId: '9',
    sortOrder: 1,
  },
  {
    id: '35',
    title: 'Zombie Shooter',
    description: '',
    thumb: `/assets/updated-games/zombie-shooter/bg-square.jpg`,
    thumbBig: `/assets/updated-games/zombie-shooter/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/zombie-shooter/index.html`,
    categoryId: '6',
    sortOrder: 1,
  },
  {
    id: '36',
    title: 'BTR 80',
    description: '',
    thumb: `/assets/updated-games/btr-80/bg-square.jpg`,
    thumbBig: `/assets/updated-games/btr-80/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/btr-80/index.html`,
    categoryId: '10',
    sortOrder: 1,
  },
  {
    id: '38',
    title: 'Crossword',
    description: '',
    thumb: `/assets/updated-games/crossword/bg-square.jpg`,
    thumbBig: `/assets/updated-games/crossword/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/crossword/index.html`,
    categoryId: '11',
    sortOrder: 5,
  },
  // ---------------------------------------------------------------------- New milan JSON ------------------------------------------------------------------------------------------
  {
    id: '40',
    title: 'MGFK',
    description: '',
    thumb: `/assets/updated-games/mgfk/bg-square.jpg`,
    thumbBig: `/assets/updated-games/mgfk/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/mgfk/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '41',
    title: 'Superpongoal',
    description: '',
    thumb: `/assets/updated-games/superpongoal/bg-square.jpg`,
    thumbBig: `/assets/updated-games/superpongoal/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/superpongoal/index.html`,
    categoryId: '7',
    sortOrder: 1,

  },
  {
    id: '43',
    title: 'Smiles',
    description: '',
    thumb: `/assets/updated-games/smiles/bg-square.jpg`,
    thumbBig: `/assets/updated-games/smiles/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/smiles/index.html`,
    categoryId: '11',
    sortOrder: 2,

  },
  {
    id: '44',
    title: 'Hotjewels',
    description: '',
    thumb: `/assets/updated-games/hotjewels/bg-square.jpg`,
    thumbBig: `/assets/updated-games/hotjewels/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/hotjewels/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '45',
    title: 'Balloon Paradise',
    description: '',
    thumb: `/assets/updated-games/balloon-paradise/bg-square.jpg`,
    thumbBig: `/assets/updated-games/balloon-paradise/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/balloon-paradise/index.html`,
    categoryId: '11',
    sortOrder: 2,

  },
  {
    id: '46',
    title: 'Touchball',
    description: '',
    thumb: `/assets/updated-games/touchball/bg-square.jpg`,
    thumbBig: `/assets/updated-games/touchball/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/touchball/index.html`,
    categoryId: '2',
    sortOrder: 5,

  },
  {
    id: '47',
    title: 'SCL',
    description: '',
    thumb: `/assets/updated-games/scl/bg-square.jpg`,
    thumbBig: `/assets/updated-games/scl/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/scl/index.html`,
    categoryId: '2',
    sortOrder: 5,

  },
  {
    id: '49',
    title: 'Professor Bubble',
    description: '',
    thumb: `/assets/updated-games/professor-bubble/bg-square.jpg`,
    thumbBig: `/assets/updated-games/professor-bubble/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/professor-bubble/index.html`,
    categoryId: '1',
    sortOrder: 2,

  },
  {
    id: '50',
    title: 'Stick Soldier',
    description: '',
    thumb: `/assets/updated-games/stick-soldier/bg-square.jpg`,
    thumbBig: `/assets/updated-games/stick-soldier/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/stick-soldier/index.html`,
    categoryId: '6',
    sortOrder: 1,

  },
  {
    id: '51',
    title: 'Mad Shark',
    description: '',
    thumb: `/assets/updated-games/mad-shark/bg-square.jpg`,
    thumbBig: `/assets/updated-games/mad-shark/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/mad-shark/index.html`,
    categoryId: '4',
    sortOrder: 1,

  },
  {
    id: '52',
    title: 'Great Air Battles',
    description: '',
    thumb: `/assets/updated-games/great-air-battles/bg-square.jpg`,
    thumbBig: `/assets/updated-games/great-air-battles/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/great-air-battles/index.html`,
    categoryId: '3',
    sortOrder: 1,

  },
  {
    id: '53',
    title: 'Quick Dice',
    description: '',
    thumb: `/assets/updated-games/quick-dice/bg-square.jpg`,
    thumbBig: `/assets/updated-games/quick-dice/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/quick-dice/index.html`,
    categoryId: '8',
    sortOrder: 2,

  },
  {
    id: '54',
    title: 'Candymatch 3',
    description: '',
    thumb: `/assets/updated-games/candymatch3/bg-square.jpg`,
    thumbBig: `/assets/updated-games/candymatch3/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/candymatch3/index.html`,
    categoryId: '2',
    sortOrder: 2,

  },
  {
    id: '55',
    title: 'Kids True Color',
    description: '',
    thumb: `/assets/updated-games/kids-true-color/bg-square.jpg`,
    thumbBig: `/assets/updated-games/kids-true-color/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/kids-true-color/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '56',
    title: 'Christmas Balloons',
    description: '',
    thumb: `/assets/updated-games/christmas-balloons/bg-square.jpg`,
    thumbBig: `/assets/updated-games/christmas-balloons/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/christmas-balloons/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '57',
    title: 'Christmas Match',
    description: '',
    thumb: `/assets/updated-games/christmasmatch/bg-square.jpg`,
    thumbBig: `/assets/updated-games/christmasmatch/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/christmasmatch/index.html`,
    categoryId: '2',
    sortOrder: 2,

  },
  {
    id: '58',
    title: 'Speed Racer',
    description: '',
    thumb: `/assets/updated-games/speedracer/bg-square.jpg`,
    thumbBig: `/assets/updated-games/speedracer/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/speedracer/index.html`,
    categoryId: '5',
    sortOrder: 1,

  },
  {
    id: '59',
    title: 'Christmas PandaRun',
    description: '',
    thumb: `/assets/updated-games/christmaspandarun/bg-square.jpg`,
    thumbBig: `/assets/updated-games/christmaspandarun/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/christmaspandarun/index.html`,
    categoryId: '3',
    sortOrder: 1,

  },
  {
    id: '60',
    title: 'Shoot Robbers',
    description: '',
    thumb: `/assets/updated-games/shootrobbers/bg-square.jpg`,
    thumbBig: `/assets/updated-games/shootrobbers/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/shootrobbers/index.html`,
    categoryId: '3',
    sortOrder: 1,

  },
  {
    id: '61',
    title: 'Jelly Match',
    description: '',
    thumb: `/assets/updated-games/jellymatch3/bg-square.jpg`,
    thumbBig: `/assets/updated-games/jellymatch3/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/jellymatch3/index.html`,
    categoryId: '2',
    sortOrder: 2,

  },
  {
    id: '62',
    title: 'Candy super Lines',
    description: '',
    thumb: `/assets/updated-games/candysuperlines/bg-square.jpg`,
    thumbBig: `/assets/updated-games/candysuperlines/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/candysuperlines/index.html`,
    categoryId: '2',
    sortOrder: 2,

  },
  {
    id: '63',
    title: 'GirlDressUp',
    description: '',
    thumb: `/assets/updated-games/girldressup/bg-square.jpg`,
    thumbBig: `/assets/updated-games/girldressup/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/girldressup/index.html`,
    categoryId: '2',
    sortOrder: 2,

  },
  {
    id: '64',
    title: 'Traffic',
    description: '',
    thumb: `/assets/updated-games/traffic/bg-square.jpg`,
    thumbBig: `/assets/updated-games/traffic/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/traffic/index.html`,
    categoryId: '10',
    sortOrder: 2,

  },
  {
    id: '65',
    title: 'Halloween Bubble Shooter',
    description: '',
    thumb: `/assets/updated-games/halloweenbubbleshooter/bg-square.jpg`,
    thumbBig: `/assets/updated-games/halloweenbubbleshooter/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/halloweenbubbleshooter/index.html`,
    categoryId: '2',
    sortOrder: 2,

  },
  {
    id: '67',
    title: 'Ranger-Zombies',
    description: '',
    thumb: `/assets/updated-games/ranger-vs-zombies/bg-square.jpg`,
    thumbBig: `/assets/updated-games/ranger-vs-zombies/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/ranger-vs-zombies/index.html`,
    categoryId: '3',
    sortOrder: 1,

  },
  {
    id: '68',
    title: 'Brickout',
    description: '',
    thumb: `/assets/updated-games/brickout/bg-square.jpg`,
    thumbBig: `/assets/updated-games/brickout/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/brickout/index.html`,
    categoryId: '2',
    sortOrder: 1,

  },
  {
    id: '69',
    title: 'Fruitsnake',
    description: '',
    thumb: `/assets/updated-games/fruitsnake/bg-square.jpg`,
    thumbBig: `/assets/updated-games/fruitsnake/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/fruitsnake/index.html`,
    categoryId: '2',
    sortOrder: 2,

  },
  {
    id: '71',
    title: 'Tankwars',
    description: '',
    thumb: `/assets/updated-games/tankwars/bg-square.jpg`,
    thumbBig: `/assets/updated-games/tankwars/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/tankwars/index.html`,
    categoryId: '6',
    sortOrder: 1,

  },
  {
    id: '72',
    title: 'Cartoon Candy',
    description: '',
    thumb: `/assets/updated-games/cartoon-candy-match3/bg-square.jpg`,
    thumbBig: `/assets/updated-games/cartoon-candy-match3/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/cartoon-candy-match3/index.html`,
    categoryId: '2',
    sortOrder: 3,

  },
  {
    id: '73',
    title: 'Flappyball',
    description: '',
    thumb: `/assets/updated-games/flappyball/bg-square.jpg`,
    thumbBig: `/assets/updated-games/flappyball/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/flappyball/index.html`,
    categoryId: '7',
    sortOrder: 1,

  },
  {
    id: '74',
    title: 'Fishworld Match3',
    description: '',
    thumb: `/assets/updated-games/fishworld-match3/bg-square.jpg`,
    thumbBig: `/assets/updated-games/fishworld-match3/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/fishworld-match3/index.html`,
    categoryId: '2',
    sortOrder: 3,

  },
  {
    id: '75',
    title: 'Easter Memory',
    description: '',
    thumb: `/assets/updated-games/eastermemory/bg-square.jpg`,
    thumbBig: `/assets/updated-games/eastermemory/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/eastermemory/index.html`,
    categoryId: '2',
    sortOrder: 4,

  },
  {
    id: '75',
    title: '2048 Master',
    description: '',
    thumb: `/assets/updated-games/2048-master/bg-square.jpg`,
    thumbBig: `/assets/updated-games/2048-master/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/2048-master/index.html`,
    categoryId: '1',
    sortOrder: 2,
  },
  {
    id: '76',
    title: 'Race Master',
    description: '',
    thumb: `/assets/updated-games/race-master/bg-square.jpg`,
    thumbBig: `/assets/updated-games/race-master/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/race-master/index.html`,
    categoryId: '5',
    sortOrder: 2,

  },
  {
    id: '77',
    title: 'Four colour',
    description: '',
    thumb: `/assets/updated-games/four-colour/bg-square.jpg`,
    thumbBig: `/assets/updated-games/four-colour/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/four-colour/index.html`,
    categoryId: '8',
    sortOrder: 3,

  },
  {
    id: '78',
    title: 'Domino Block',
    description: '',
    thumb: `/assets/updated-games/domino-block/bg-square.jpg`,
    thumbBig: `/assets/updated-games/domino-block/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/domino-block/index.html`,
    categoryId: '1',
    sortOrder: 3,

  },
  {
    id: '79',
    title: 'Penalty Challange',
    description: '',
    thumb: `/assets/updated-games/penalty-challange/bg-square.jpg`,
    thumbBig: `/assets/updated-games/penalty-challange/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/penalty-challange/index.html`,
    categoryId: '7',
    sortOrder: 1,

  },
  {
    id: '80',
    title: 'Fantasty Forest',
    description: '',
    thumb: `/assets/updated-games/fantasty-forest/bg-square.jpg`,
    thumbBig: `/assets/updated-games/fantasty-forest/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/fantasty-forest/index.html`,
    categoryId: '2',
    sortOrder: 3,

  },
  {
    id: '81',
    title: 'Hacker Challange',
    description: '',
    thumb: `/assets/updated-games/hacker-challange/bg-square.jpg`,
    thumbBig: `/assets/updated-games/hacker-challange/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/hacker-challange/index.html`,
    categoryId: '2',
    sortOrder: 3,

  },
  {
    id: '82',
    title: 'Lottery Numbers',
    description: '',
    thumb: `/assets/updated-games/lottery-numbers/bg-square.jpg`,
    thumbBig: `/assets/updated-games/lottery-numbers/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/lottery-numbers/index.html`,
    categoryId: '2',
    sortOrder: 3,

  },
  // New games
  {
    id: '171',
    title: 'Teddy Escape',
    description: '',
    thumb: `/assets/updated-games/Teddy_Escape/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Teddy_Escape/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Teddy_Escape/index.html`,
    categoryId: '11',
    sortOrder: 2,

  },
  {
    id: '83',
    title: '2 Ballons',
    description: '',
    thumb: `/assets/updated-games/2_ballon_shooter/bg-square.jpg`,
    thumbBig: `/assets/updated-games/2_ballon_shooter/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/2_ballon_shooter/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '85',
    title: 'Pixel Jet Fighters',
    description: '',
    thumb: `/assets/updated-games/2_Pixel_Jet_Fighters/bg-square.jpg`,
    thumbBig: `/assets/updated-games/2_Pixel_Jet_Fighters/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/2_Pixel_Jet_Fighters/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '87',
    title: '4 Colors Challenge',
    description: '',
    thumb: `/assets/updated-games/4_Colors_Challenge/bg-square.jpg`,
    thumbBig: `/assets/updated-games/4_Colors_Challenge/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/4_Colors_Challenge/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '88',
    title: '90 Degrees',
    description: '',
    thumb: `/assets/updated-games/90_Degrees/bg-square.jpg`,
    thumbBig: `/assets/updated-games/90_Degrees/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/90_Degrees/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '90',
    title: 'AA Touch Gun',
    description: '',
    thumb: `/assets/updated-games/AA_Touch_Gun/bg-square.jpg`,
    thumbBig: `/assets/updated-games/AA_Touch_Gun/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/AA_Touch_Gun/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '91',
    title: 'ABC Jump',
    description: '',
    thumb: `/assets/updated-games/ABC_Jump/bg-square.jpg`,
    thumbBig: `/assets/updated-games/ABC_Jump/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/ABC_Jump/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '92',
    title: 'Alien Attack',
    description: '',
    thumb: `/assets/updated-games/Alien_Attack/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Alien_Attack/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Alien_Attack/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '93',
    title: 'Alphabet Memory',
    description: '',
    thumb: `/assets/updated-games/Alphabet_Memory/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Alphabet_Memory/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Alphabet_Memory/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '94',
    title: 'Animal Fall',
    description: '',
    thumb: `/assets/updated-games/Animal_Fall/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Animal_Fall/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Animal_Fall/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '95',
    title: 'Animals Shapes',
    description: '',
    thumb: `/assets/updated-games/Animals_Shapes/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Animals_Shapes/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Animals_Shapes/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '96',
    title: 'Aqua Challenge',
    description: '',
    thumb: `/assets/updated-games/Aqua_Challenge/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Aqua_Challenge/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Aqua_Challenge/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '97',
    title: 'Army Bomber Truck',
    description: '',
    thumb: `/assets/updated-games/Army_Bomber_Truck/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Army_Bomber_Truck/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Army_Bomber_Truck/index.html`,
    categoryId: '10',
    sortOrder: 1,

  },
  {
    id: '98',
    title: 'Big Must Jump',
    description: '',
    thumb: `/assets/updated-games/Big_Must_Jump/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Big_Must_Jump/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Big_Must_Jump/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '99',
    title: 'Black Star Pinball',
    description: '',
    thumb: `/assets/updated-games/Black_Star_Pinball/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Black_Star_Pinball/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Black_Star_Pinball/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '100',
    title: 'Blow Horn',
    description: '',
    thumb: `/assets/updated-games/Blow_Horn/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Blow_Horn/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Blow_Horn/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '101',
    title: 'Elementary arithmetic Game',
    description: '',
    thumb: `/assets/updated-games/Elementary_arithmetic_Game/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Elementary_arithmetic_Game/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Elementary_arithmetic_Game/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '102',
    title: 'Face changer',
    description: '',
    thumb: `/assets/updated-games/Face_changer/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Face_changer/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Face_changer/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '103',
    title: 'Falling Balls',
    description: '',
    thumb: `/assets/updated-games/Falling_Balls/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Falling_Balls/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Falling_Balls/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '104',
    title: 'Farm Animals Kids',
    description: '',
    thumb: `/assets/updated-games/Farm_Animals_-_Kids/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Farm_Animals_-_Kids/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Farm_Animals_-_Kids/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '105',
    title: 'Flap Bee',
    description: '',
    thumb: `/assets/updated-games/Flap_Bee/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Flap_Bee/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Flap_Bee/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '106',
    title: 'Flappy Bat',
    description: '',
    thumb: `/assets/updated-games/Flappy_Bat/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Flappy_Bat/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Flappy_Bat/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '107',
    title: 'Foot Doctor',
    description: '',
    thumb: `/assets/updated-games/Foot_Doctor/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Foot_Doctor/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Foot_Doctor/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '108',
    title: 'Galaxy and Stone',
    description: '',
    thumb: `/assets/updated-games/Galaxy_and_Stone/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Galaxy_and_Stone/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Galaxy_and_Stone/index.html`,
    categoryId: '11',
    sortOrder: 2,

  },
  {
    id: '109',
    title: 'Halloween Defence',
    description: '',
    thumb: `/assets/updated-games/Halloween_Defence/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Halloween_Defence/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Halloween_Defence/index.html`,
    categoryId: '6',
    sortOrder: 3,

  },
  {
    id: '110',
    title: 'Hand Doctor',
    description: '',
    thumb: `/assets/updated-games/Hand_Doctor/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Hand_Doctor/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Hand_Doctor/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '111',
    title: 'Boom Room',
    description: '',
    thumb: `/assets/updated-games/Boom_Room/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Boom_Room/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Boom_Room/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '112',
    title: 'Bow-Hunter',
    description: '',
    thumb: `/assets/updated-games/Bow_and_Hunter/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Bow_and_Hunter/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Bow_and_Hunter/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '113',
    title: 'Choli Food Drop',
    description: '',
    thumb: `/assets/updated-games/Choli_-_Food_Drop/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Choli_-_Food_Drop/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Choli_-_Food_Drop/index.html`,
    categoryId: '11',
    sortOrder: 2,

  },
  {
    id: '114',
    title: 'Choli Climb',
    description: '',
    thumb: `/assets/updated-games/Choli_Climb/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Choli_Climb/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Choli_Climb/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '115',
    title: 'Choli Jet',
    description: '',
    thumb: `/assets/updated-games/Choli_Jet/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Choli_Jet/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Choli_Jet/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '116',
    title: 'Choli Water',
    description: '',
    thumb: `/assets/updated-games/Choli_Water_Hop/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Choli_Water_Hop/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Choli_Water_Hop/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '117',
    title: 'Circle Runner',
    description: '',
    thumb: `/assets/updated-games/Circle_Runner/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Circle_Runner/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Circle_Runner/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '118',
    title: 'City Defender',
    description: '',
    thumb: `/assets/updated-games/City_Defender/bg-square.jpg`,
    thumbBig: `/assets/updated-games/City_Defender/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/City_Defender/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '119',
    title: 'Classic Helicopter',
    description: '',
    thumb: `/assets/updated-games/Classic_Helicopter_Game/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Classic_Helicopter_Game/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Classic_Helicopter_Game/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '120',
    title: 'Classic Puzzle Game',
    description: '',
    thumb: `/assets/updated-games/Classic_Puzzle_Game/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Classic_Puzzle_Game/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Classic_Puzzle_Game/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '121',
    title: 'Clock Challenge',
    description: '',
    thumb: `/assets/updated-games/Clock_Challenge/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Clock_Challenge/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Clock_Challenge/index.html`,
    categoryId: '11',
    sortOrder: 3,

  },
  {
    id: '122',
    title: 'Color Pong',
    description: '',
    thumb: `/assets/updated-games/Color_Pong/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Color_Pong/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Color_Pong/index.html`,
    categoryId: '11',
    sortOrder: 4,

  },
  {
    id: '123',
    title: 'Colored Circle',
    description: '',
    thumb: `/assets/updated-games/Colored_Circle_2!/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Colored_Circle_2!/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Colored_Circle_2!/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '124',
    title: 'Colored Square',
    description: '',
    thumb: `/assets/updated-games/Colored_Square/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Colored_Square/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Colored_Square/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '125',
    title: 'Colorful Clock',
    description: '',
    thumb: `/assets/updated-games/Colorful_Clock/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Colorful_Clock/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Colorful_Clock/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '126',
    title: 'Coloring Book',
    description: '',
    thumb: `/assets/updated-games/Coloring_Book/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Coloring_Book/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Coloring_Book/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '127',
    title: 'Count the Cards',
    description: '',
    thumb: `/assets/updated-games/Count_the_Cards/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Count_the_Cards/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Count_the_Cards/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '128',
    title: 'Dangerous Circle',
    description: '',
    thumb: `/assets/updated-games/Dangerous_Circle/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Dangerous_Circle/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Dangerous_Circle/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '129',
    title: 'Dodge or Die',
    description: '',
    thumb: `/assets/updated-games/Dodge_or_Die/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Dodge_or_Die/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Dodge_or_Die/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '130',
    title: 'Duck Hunter',
    description: '',
    thumb: `/assets/updated-games/Duck_Hunter/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Duck_Hunter/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Duck_Hunter/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '131',
    title: 'Hard Flap',
    description: '',
    thumb: `/assets/updated-games/Hard_Flap/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Hard_Flap/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Hard_Flap/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '132',
    title: 'Hard Glass',
    description: '',
    thumb: `/assets/updated-games/Hard_Glass/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Hard_Glass/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Hard_Glass/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '133',
    title: 'Heli Defence',
    description: '',
    thumb: `/assets/updated-games/HeliDefence/bg-square.jpg`,
    thumbBig: `/assets/updated-games/HeliDefence/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/HeliDefence/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '134',
    title: 'Honey Drop',
    description: '',
    thumb: `/assets/updated-games/Honey_Drop/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Honey_Drop/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Honey_Drop/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '135',
    title: 'Honey Thief',
    description: '',
    thumb: `/assets/updated-games/Honey_Thief/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Honey_Thief/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Honey_Thief/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '136',
    title: 'Hungry Number',
    description: '',
    thumb: `/assets/updated-games/Hungry_Number/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Hungry_Number/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Hungry_Number/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '137',
    title: 'Island Defender',
    description: '',
    thumb: `/assets/updated-games/Island_Defender/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Island_Defender/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Island_Defender/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '138',
    title: 'Jet Halloween',
    description: '',
    thumb: `/assets/updated-games/Jet_Halloween/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Jet_Halloween/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Jet_Halloween/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '139',
    title: 'Jugglers Battle',
    description: '',
    thumb: `/assets/updated-games/Jugglers_Battle/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Jugglers_Battle/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Jugglers_Battle/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '140',
    title: 'Kids Country',
    description: '',
    thumb: `/assets/updated-games/Kids_Country_Flag_Quiz/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Kids_Country_Flag_Quiz/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Kids_Country_Flag_Quiz/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '141',
    title: 'Kids Halloween',
    description: '',
    thumb: `/assets/updated-games/Kids_Halloween/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Kids_Halloween/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Kids_Halloween/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '142',
    title: 'Kids Mathematics',
    description: '',
    thumb: `/assets/updated-games/Kids_Mathematics/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Kids_Mathematics/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Kids_Mathematics/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '143',
    title: 'Lake Ride',
    description: '',
    thumb: `/assets/updated-games/Lake_Ride/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Lake_Ride/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Lake_Ride/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '144',
    title: 'Mafia Agent',
    description: '',
    thumb: `/assets/updated-games/Mafia_Agent/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Mafia_Agent/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Mafia_Agent/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '145',
    title: 'Make Little Boy',
    description: '',
    thumb: `/assets/updated-games/Make_Your_Little_Boy/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Make_Your_Little_Boy/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Make_Your_Little_Boy/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '146',
    title: 'Maze-Tourist',
    description: '',
    thumb: `/assets/updated-games/Maze_And_Tourist/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Maze_And_Tourist/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Maze_And_Tourist/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '147',
    title: 'Memory Challenge',
    description: '',
    thumb: `/assets/updated-games/Memory_Challenge/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Memory_Challenge/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Memory_Challenge/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '148',
    title: 'Monster Eye',
    description: '',
    thumb: `/assets/updated-games/Monster_Of_Eye/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Monster_Of_Eye/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Monster_Of_Eye/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '149',
    title: 'Monster truck',
    description: '',
    thumb: `/assets/updated-games/Monster_truck/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Monster_truck/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Monster_truck/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '150',
    title: 'Motocross Xtreme',
    description: '',
    thumb: `/assets/updated-games/Motocross_Xtreme/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Motocross_Xtreme/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Motocross_Xtreme/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  // Pending
  {
    id: '151',
    title: 'Narrow Halloween',
    description: '',
    thumb: `/assets/updated-games/Narrow_Passage_For_Halloween/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Narrow_Passage_For_Halloween/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Narrow_Passage_For_Halloween/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '152',
    title: 'Ninja Fishing',
    description: '',
    thumb: `/assets/updated-games/Ninja_Fishing/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Ninja_Fishing/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Ninja_Fishing/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '153',
    title: 'Ninja Pumpkin',
    description: '',
    thumb: `/assets/updated-games/Ninja_Pumpkin/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Ninja_Pumpkin/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Ninja_Pumpkin/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '154',
    title: 'Number Jump',
    description: '',
    thumb: `/assets/updated-games/Number_Jump/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Number_Jump/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Number_Jump/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '155',
    title: 'Punch Box',
    description: '',
    thumb: `/assets/updated-games/Punch_Box/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Punch_Box/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Punch_Box/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '156',
    title: 'Quick Color',
    description: '',
    thumb: `/assets/updated-games/Quick_Color_Tap!/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Quick_Color_Tap!/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Quick_Color_Tap!/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '157',
    title: 'Rectangular Path',
    description: '',
    thumb: `/assets/updated-games/Rectangular_Path/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Rectangular_Path/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Rectangular_Path/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '158',
    title: 'Ricocheting Ball',
    description: '',
    thumb: `/assets/updated-games/Ricocheting_Ball/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Ricocheting_Ball/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Ricocheting_Ball/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '159',
    title: 'Rock Paper Scissors',
    description: '',
    thumb: `/assets/updated-games/Rock_Paper_Scissors/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Rock_Paper_Scissors/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Rock_Paper_Scissors/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '160',
    title: 'Roll Orange',
    description: '',
    thumb: `/assets/updated-games/Roll_Orange/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Roll_Orange/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Roll_Orange/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '161',
    title: 'Save the Miner',
    description: '',
    thumb: `/assets/updated-games/Save_the_Miner/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Save_the_Miner/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Save_the_Miner/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '162',
    title: 'Shadow Fighter',
    description: '',
    thumb: `/assets/updated-games/Shadow_Fighter/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Shadow_Fighter/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Shadow_Fighter/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '163',
    title: 'Sky Jump',
    description: '',
    thumb: `/assets/updated-games/Sky_Jump_-_KARA/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Sky_Jump_-_KARA/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Sky_Jump_-_KARA/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '164',
    title: 'Smash Ant',
    description: '',
    thumb: `/assets/updated-games/Smash_the_Ant/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Smash_the_Ant/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Smash_the_Ant/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '165',
    title: 'Snake Ladders',
    description: '',
    thumb: `/assets/updated-games/Snake_&__Ladders/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Snake_&__Ladders/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Snake_&__Ladders/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '166',
    title: 'Snake Eater',
    description: '',
    thumb: `/assets/updated-games/Snake_-_Egg_Eater/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Snake_-_Egg_Eater/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Snake_-_Egg_Eater/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '167',
    title: 'Speedy Fish',
    description: '',
    thumb: `/assets/updated-games/Speedy_Fish/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Speedy_Fish/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Speedy_Fish/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '168',
    title: 'stickman fighter',
    description: '',
    thumb: `/assets/updated-games/stickman_fighter/bg-square.jpg`,
    thumbBig: `/assets/updated-games/stickman_fighter/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/stickman_fighter/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '170',
    title: 'Tank Strategy',
    description: '',
    thumb: `/assets/updated-games/Tank_Strategy/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Tank_Strategy/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Tank_Strategy/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '172',
    title: 'Tiny Alien_spaceship',
    description: '',
    thumb: `/assets/updated-games/Tiny_Alien_spaceship/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Tiny_Alien_spaceship/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Tiny_Alien_spaceship/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '173',
    title: 'Touch Fishing',
    description: '',
    thumb: `/assets/updated-games/Touch_Fishing/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Touch_Fishing/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Touch_Fishing/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '174',
    title: 'Up Down Ninja',
    description: '',
    thumb: `/assets/updated-games/Up_Down_Ninja/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Up_Down_Ninja/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Up_Down_Ninja/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '175',
    title: 'War Plane',
    description: '',
    thumb: `/assets/updated-games/War_Plane/bg-square.jpg`,
    thumbBig: `/assets/updated-games/War_Plane/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/War_Plane/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '176',
    title: 'Water Cleaner',
    description: '',
    thumb: `/assets/updated-games/Water_Cleaner/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Water_Cleaner/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Water_Cleaner/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '177',
    title: 'Wrestling',
    description: '',
    thumb: `/assets/updated-games/Wrestling/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Wrestling/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Wrestling/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '178',
    title: 'Air Battle',
    description: '',
    thumb: `/assets/updated-games/WWII_Air_Battle/bg-square.jpg`,
    thumbBig: `/assets/updated-games/WWII_Air_Battle/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/WWII_Air_Battle/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
  {
    id: '179',
    title: 'Surgical Strike',
    description: '',
    thumb: `/assets/updated-games/Surgical_Strike/bg-square.jpg`,
    thumbBig: `/assets/updated-games/Surgical_Strike/bg-thumbnail.jpg`,
    url: `${environment.gameUrl}/Surgical_Strike/index.html`,
    categoryId: '11',
    sortOrder: 5,

  },
];
export const GameMenuList: Array<MenuListModel> = [
  {
    id: '1',
    title: 'Strategy',
    icon: 'strategy',
    category: 'strategy',
  },
  {
    id: '2',
    title: 'Puzzle',
    icon: 'puzzle',
    category: 'puzzle',
  },
  {
    id: '3',
    title: 'Action',
    icon: 'action',
    category: 'action',
  },
  {
    id: '4',
    title: 'Adventure',
    icon: 'adventure',
    category: 'adventure',
  },
  {
    id: '5',
    title: 'Racing',
    icon: 'racing',
    category: 'racing',
  },
  {
    id: '6',
    title: 'Horror',
    icon: 'horror',
    category: 'horror',
  },
  {
    id: '7',
    title: 'Sports',
    icon: 'sports',
    category: 'sports',
  },
  {
    id: '8',
    title: 'Card',
    icon: 'card',
    category: 'card',
  },
  {
    id: '9',
    title: 'Bike',
    icon: 'bike',
    category: 'bike',
  },
  {
    id: '10',
    title: 'Driving',
    icon: 'driving',
    category: 'driving',
  },
  {
    id: '11',
    title: 'Kids',
    icon: 'kids',
    category: 'kids',
  },
];
export const GameMenuListHot: Array<MenuListModel> = [
  {
    id: '5',
    title: 'Racing',
    icon: 'racing',
    category: 'racing',
  },
  // {
  //   id: '1',
  //   title: 'Strategy',
  //   icon: 'strategy',
  //   category: 'strategy',
  // },
  {
    id: '2',
    title: 'Puzzle',
    icon: 'puzzle',
    category: 'puzzle',
  },
  {
    id: '3',
    title: 'Shooting',
    icon: 'shooting',
    category: 'shooting',
  },
  {
    id: '4',
    title: 'Adventure',
    icon: 'adventure',
    category: 'adventure',
  },
  // {
  //   id: '6',
  //   title: 'Horror',
  //   icon: 'horror',
  //   category: 'horror',
  // },
  {
    id: '7',
    title: 'Sports',
    icon: 'sports',
    category: 'sports',
  },
  // {
  //   id: '8',
  //   title: 'Card',
  //   icon: 'card',
  //   category: 'card',
  // },
  // {
  //   id: '9',
  //   title: 'Bike',
  //   icon: 'bike',
  //   category: 'bike',
  // },
  // {
  //   id: '10',
  //   title: 'Driving',
  //   icon: 'driving',
  //   category: 'driving',
  // },
  // {
  //   id: '11',
  //   title: 'Kids',
  //   icon: 'kids',
  //   category: 'kids',
  // },
  {
    id: '12',
    title: 'Girls',
    icon: 'girls',
    category: 'girls',
  },
  {
    id: '13',
    title: 'Arcade',
    icon: 'Arcade',
    category: 'arcade',
  },
  {
    id: '14',
    title: 'Hypercasual',
    icon: 'Hypercasual',
    category: 'hypercasual',
  },
  {
    id: '15',
    title: 'Action',
    icon: 'action',
    category: 'action',
  },
];
export const GameListHot: Array<GameModelHot> = [
  {
    "id": "55092",
    "title": "Sandwich Runner 2",
    "description": "Sandwich Runner is a fun game. Collect ingredients on the way to the goal, how high will it reach? The diner is very hungry and he cant wait to eat. Collect steaks, chicken thighs, fried eggs, and sushi. Be careful to avoid bad food like mold and rot or it will make the diner sick! Red peppers will make the diner spitfire! Can you keep the diner happy and pass the level? Good luck! Website Developer <a href='https:\/\/www.insanegamesonline.com\/'>https:\/\/www.insanegamesonline.com\/<\/a>",
    "instructions": "Mouse click or tap to play",
    "url": "https://html5.gamemonetize.com/iqn1x8vicafzb829as61fir70revvb8v/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "Food",
    "thumb": "https://img.gamemonetize.com/iqn1x8vicafzb829as61fir70revvb8v/512x384.jpg",
    "width": "750",
    "height": "1334"
  },
  {
    "id": "55081",
    "title": "Monster Truck Crush",
    "description": "Monster Truck Crush is a skillful balanced monster truck racing arcade game. With 3D monster trucks, you need to defeat the AI opponent by arriving at the finish line in the first place. You can speed up immediately when your vehicle is balanced on the next platform. Or else, you will lose some speed or roll the truck. The AI opponent is good at controlling the speed. But you can control the body angle of the car to keep speeding up. Good luck!",
    "instructions": "Mouse click or tap to play",
    "url": "https://html5.gamemonetize.com/t1hio10b5dvpe4c6whabcb5g28q6kc34/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "Car, Truck",
    "thumb": "https://img.gamemonetize.com/t1hio10b5dvpe4c6whabcb5g28q6kc34/512x384.jpg",
    "width": "750",
    "height": "1630"
  },
  {
    "id": "43596",
    "title": "Low Poly Smash Cars",
    "description": "Welcome! It's the season for total destruction! This Demolition Derby is all about crazy racing manoeuvres and crushing your opponents cars. Choose your favourite Super Car model and enter the twisted derby arena, Start accelerating and cause damage on the cars that stay on your way. Put your reckless driving skills and crashing talents to the test in this exciting new arena game of destruction! Be the last man standing to advance to the next level. Enjoy smooth driving simulations and high quality graphics!",
    "instructions": "Drive ARROW KEYS Handbrake SPACEBAR Menus LEFT MOUSE BUTTON",
    "url": "https://html5.gamemonetize.com/9bz11r8r0jtt3c5mpbcbzkyd1b24gtuz/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "1 Player, 3D, 3D Games, Action, Arena, Battle, Car, Cars, Cool, Crazy, drift, Driving, HTML5, New, Race, Racing, Skill, Skills, Stunts, Supercars, Unity3D, WebGL",
    "thumb": "https://img.gamemonetize.com/9bz11r8r0jtt3c5mpbcbzkyd1b24gtuz/512x384.jpg",
    "width": "900",
    "height": "600"
  },
  {
    "id": "54782",
    "title": "Bike Stunt Racing Legend",
    "description": "Bike Stunt Racing Legend is not merely a motorcycle racing but also a balanced stunt simulation game. Under a 3D game engine, you are required to ride the motorbike to the finish line in the first place. As long as you can keep high speed, the AI opponent will make mistakes and lose you. Dont be afraid of rolling ramps, pass the green arrows to speed up more easily. Keep calm and step on the gas!",
    "instructions": "Mouse click or tap to play",
    "url": "https://html5.gamemonetize.com/zfw0fws86pljd7j9ic8afnmnw8hkjbmg/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "Bike",
    "thumb": "https://img.gamemonetize.com/zfw0fws86pljd7j9ic8afnmnw8hkjbmg/512x384.jpg",
    "width": "1630",
    "height": "750"
  },
  {
    "id": "53823",
    "title": "Dinosaur Runner 3D",
    "description": "How do you like dinosaurs? Dinosaur Runner 3D offers you a chance to gather more dinosaurs to make a dinosaur army and defeat your enemies. Collect the dinosaurs and pass the blue numbered walls to increase the number of your army. Dodge all kinds of trap obstacles and red-numbered walls to avoid unnecessary downsizing. Use the ramps to jump over the obstacles you cant walk through directly. Buy more units to win the final battle!",
    "instructions": "Mouse click or tap to play",
    "url": "https://html5.gamemonetize.com/lt746oobrexlzvtpaggqnkyhp79ugcu0/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "running",
    "thumb": "https://img.gamemonetize.com/lt746oobrexlzvtpaggqnkyhp79ugcu0/512x384.jpg",
    "width": "720",
    "height": "1560"
  },
  {
    "id": "54468",
    "title": "Taxi Driver Las Vegas",
    "description": "Are you prepared to play an awesome simulator? Taxi Driver Las Vegas is an online game set in an open environment with objectives to help you improve your cab driving abilities. Pick up the passengers and drive them to their destination, following the directions and exploring all of the maps to locate the streets and addresses. This game includes many game modes to keep you entertained; you can accomplish the stages in taxi or open mode and freely explore the whole landscape.",
    "instructions": "Controls WASD to move Click to move the camera C Camera Spacebar Jump Ctr to Run F Interact Esc Menu",
    "url": "https://html5.gamemonetize.com/stz0s4mvb541uczwkkr918qkwfzuigl8/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "3D Games, Car, car tuning, Driving, kiz10",
    "thumb": "https://img.gamemonetize.com/stz0s4mvb541uczwkkr918qkwfzuigl8/512x384.jpg",
    "width": "900",
    "height": "600"
  },
  {
    "id": "54693",
    "title": "Speed Racer Higway 3D",
    "description": "Speed Racer Highway 3D is an exhilarating 3D driving game where players navigate a high-speed car along a bustling highway. The challenge lies in dodging relentless traffic and obstacles while maintaining high speeds to score points. Players must master quick reflexes and strategic timing to avoid crashes. The game features vibrant graphics, multiple car options, and escalating difficulty levels. Website Developer <a href='https://www.playbestgames.io/'>https://www.playbestgames.io/</a>",
    "instructions": "WASD control the car",
    "url": "https://html5.gamemonetize.com/cv7jmbhcg4jqb98eanshnnhhfi1u6ex3/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "1 Player, Action, Arcade, Car, Driving, Race, Racing, unity",
    "thumb": "https://img.gamemonetize.com/cv7jmbhcg4jqb98eanshnnhhfi1u6ex3/512x384.jpg",
    "width": "800",
    "height": "600"
  },
  {
    "id": "54153",
    "title": "Biking Extreme 3D",
    "description": "Do you like riding a mountain bike? Biking Extreme 3D offers you a chance to ride a mountain bike and challenge multiplayer mountain racing tracks. It doesnt matter when you crash any other riders on the track, they will be crashed into the sky. But please always keep a safe distance between your vehicle and obstacles like trees and rocks. Or else, you will lose the game directly. The coins you won are used to upgrade your bike. Dont forget to try another 5 characters!",
    "instructions": "Mouse click or tap to play",
    "url": "https://html5.gamemonetize.com/ty6rw942yunp7e9c9knxbnt7i46g4mk5/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "Bike",
    "thumb": "https://img.gamemonetize.com/ty6rw942yunp7e9c9knxbnt7i46g4mk5/512x384.jpg",
    "width": "720",
    "height": "1280"
  },
  {
    "id": "54112",
    "title": "Mega Ramp Car Stunts",
    "description": "Mega Ramp Car Stunts plays like a hard-core stunt car-driving simulation game. With 3D obstacles on the track, you have a chance to challenge 10 levels in the Stunt Mode and 16 levels in the Giant Ramp mode. Whether you meet checkpoints or not, you need to drive the car to the finish line safely. Dont forget to buy better vehicles in the garage when you have enough green diamonds.",
    "instructions": "Mouse click or tap to play",
    "url": "https://html5.gamemonetize.com/wog31m5sqo7jh1ww71tv66ax28cn2zwb/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "Car",
    "thumb": "https://img.gamemonetize.com/wog31m5sqo7jh1ww71tv66ax28cn2zwb/512x384.jpg",
    "width": "1334",
    "height": "750"
  },
  {
    "id": "54159",
    "title": "FunnyVehicles",
    "description": "Experience thrilling races like never before! Navigate through dynamically generated levels with obstacles, ramps, and stickmen. Each level is unique, generated as you play. Test your luck with the wheel of fortune for exciting rewards. Customize your cars, buy new ones, and show off your driving skills in this adrenaline-pumping race against time and obstacles. Its not just a race; its a unique adventure every time you play! Get ready to race and conquer the track in this ultimate racing challenge!",
    "instructions": "Turn A D or arrow keys Brake Space Or Tap on-screen buttons",
    "url": "https://html5.gamemonetize.com/375jnz9zls4s27ku5pqhsin4fv5dybr7/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "Cars, drift, drifting, Driving, Funny, offroad, Online, Road, Stickman",
    "thumb": "https://img.gamemonetize.com/375jnz9zls4s27ku5pqhsin4fv5dybr7/512x384.jpg",
    "width": "1920",
    "height": "1080"
  },
  {
    "id": "54034",
    "title": "Extreme Car Driving Parking",
    "description": "In this Extreme Car Driving simulator game 2024, you will enjoy driving and parking levels. You may have played many real car parking games but this parking simulator 2024 is different from all those car driving games as you have to obey all traffic rules to park your modern car in the parking zone. Get these free 3D car games to enjoy every level of ultimate car driving &amp; parking games.",
    "instructions": "Keyboard Arrow Controls",
    "url": "https://html5.gamemonetize.com/2a2sf2gg8nebhjofqsknb3pwm8oeb09h/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "3D, 3D Games, Best, Best Games, Car, Cars, drift, drifting, Driving, Supercars",
    "thumb": "https://img.gamemonetize.com/2a2sf2gg8nebhjofqsknb3pwm8oeb09h/512x384.jpg",
    "width": "800",
    "height": "600"
  },
  {
    "id": "54102",
    "title": "Racer Car",
    "description": "In the game Racer Car, players are invited to an exhilarating adventure that tests their speed, reflexes, and concentration. While navigating a car on the highway, the goal is to travel as far as possible without colliding with other vehicles. This game challenges players skills in speed, reaction time, and maintaining focus. Every passing second increases the players score, encouraging them to play for longer durations to achieve higher scores. Racer Car offers simple controls, stunning graphics, and addictive gameplay that captivates players and keeps them glued to the screen. Test your skills to become the king of the highway and",
    "instructions": "Press the A key to move the car to the left Press the D key to move the car to the right On mobile devices players can simply swipe their finger left or right on the screen to move the car accordingly ",
    "url": "https://html5.gamemonetize.com/42ucmu37n3xevd1ioild098lowwpzjob/",
    "category": "Racing",
    "categoryId": "5",
    "tags": "1 Player, Cars, Racing",
    "thumb": "https://img.gamemonetize.com/42ucmu37n3xevd1ioild098lowwpzjob/512x384.jpg",
    "width": "1080",
    "height": "1920"
  },
];
export const SidebarMenuList: Array<MenuListModel> = [
  {
    id: '1',
    title: 'Home',
    icon: 'fa fa-home',
    routing: ['/home'],
    enum: 'HOME'
  },
  {
    id: '5',
    title: 'Hot games',
    icon: 'fa-solid fa-fire',
    routing: ['/hot'],
    enum: 'HOT'
  },
  {
    id: '2',
    title: 'Recent',
    icon: 'fa-solid fa-magnifying-glass',
    routing: ['/recent'],
    enum: 'RECENT'
  },
  {
    id: '3',
    title: 'Trending',
    icon: 'fa-solid fa-rocket',
    routing: ['/trending'],
    enum: 'TRENDING'
  },
  {
    id: '4',
    title: 'Latest',
    icon: 'fa-solid fa-gamepad',
    routing: ['/latest'],
    enum: 'LATEST'
  },
  {
    id: '5',
    title: 'Featured',
    icon: 'fa-solid fa-sliders',
    routing: ['/featured'],
    enum: 'FEATURED'
  },
];
// export const GameListHot: Array<CategoryListModel> =
